/**
 * @file compare_kiwipete_implementations.cpp  
 * @brief Compare traditional piece list vs bitboard move generation for Kiwipete position
 * 
 * This program compares the moves generated by:
 * 1. Traditional piece list implementation (generate_all_moves)
 * 2. Bitboard implementation (generate_all_moves_bitboard)
 * 
 * The goal is to identify why VICE shows 50 moves while bitboard shows 48 moves.
 */
#include <iostream>
#include <vector>
#include <set>
#include <string>
#include <iomanip>
#include "position.hpp"
#include "movegen_enhanced.hpp"
#include "bitboard_movegen.hpp"
#include "pawn_optimizations.hpp"
#include "knight_optimizations.hpp"
#include "sliding_piece_optimizations.hpp"
#include "king_optimizations.hpp"
#include "king_lookup_tables.hpp"
#include "init.hpp"

// Function to convert move to readable string
std::string move_to_string(const S_MOVE& move) {
    int from = move.get_from();
    int to = move.get_to();
    
    // Convert to algebraic notation
    std::string from_str = "";
    std::string to_str = "";
    
    // Convert 120-square to algebraic
    if (from >= 21 && from <= 98) {
        int file = (from % 10) - 1;
        int rank = (from / 10) - 2;
        if (file >= 0 && file < 8 && rank >= 0 && rank < 8) {
            from_str = char('a' + file);
            from_str += char('1' + rank);
        }
    }
    
    if (to >= 21 && to <= 98) {
        int file = (to % 10) - 1;
        int rank = (to / 10) - 2;
        if (file >= 0 && file < 8 && rank >= 0 && rank < 8) {
            to_str = char('a' + file);
            to_str += char('1' + rank);
        }
    }
    
    std::string result = from_str + to_str;
    
    if (move.is_promotion()) {
        // Add promotion piece
        PieceType promoted = move.get_promoted();
        switch (promoted) {
            case PieceType::Queen: result += "q"; break;
            case PieceType::Rook: result += "r"; break;
            case PieceType::Bishop: result += "b"; break;
            case PieceType::Knight: result += "n"; break;
            default: break;
        }
    }
    
    return result;
}

int main() {
    // Initialize the chess engine
    Huginn::init();
    
    std::cout << "=== Kiwipete Position Move Generation Comparison ===" << std::endl;
    std::cout << "Comparing traditional piece list vs bitboard implementations" << std::endl << std::endl;
    
    // Kiwipete position
    std::string kiwipete_fen = "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1";
    
    Position pos;
    if (!pos.set_from_fen(kiwipete_fen)) {
        std::cerr << "Failed to parse Kiwipete FEN!" << std::endl;
        return 1;
    }
    
    std::cout << "Position: " << kiwipete_fen << std::endl << std::endl;
    
    // Generate moves with traditional piece list implementation
    S_MOVELIST piece_list_moves;
    piece_list_moves.count = 0;
    
    // We need to force use of the traditional piece list implementation
    // The generate_all_moves function uses #ifdef BITBOARD_ENGINE to choose implementation
    // For debugging purposes, we'll call the specific piece generation functions directly
    
    Color us = pos.side_to_move;
    
    // Use the traditional piece list implementation components directly
    // This bypasses the #ifdef BITBOARD_ENGINE check in generate_all_moves
    PawnOptimizations::generate_pawn_moves_template(pos, piece_list_moves, us);
    KnightOptimizations::generate_knight_moves_template(pos, piece_list_moves, us);
    SlidingPieceOptimizations::generate_all_sliding_moves_optimized(pos, piece_list_moves, us);
    KingOptimizations::generate_king_moves_optimized(pos, piece_list_moves, us);
    KingLookupTables::generate_castling_moves_optimized(pos, piece_list_moves, us);
    
    // Generate moves with bitboard implementation
    S_MOVELIST bitboard_moves;
    BitboardMoveGen::generate_all_moves_bitboard(pos, bitboard_moves);
    
    std::cout << "Traditional piece list: " << piece_list_moves.count << " moves" << std::endl;
    std::cout << "Bitboard implementation: " << bitboard_moves.count << " moves" << std::endl << std::endl;
    
    // Convert moves to sets for comparison
    std::set<std::string> piece_list_set;
    std::set<std::string> bitboard_set;
    
    std::cout << "=== Traditional Piece List Moves ===" << std::endl;
    for (int i = 0; i < piece_list_moves.count; i++) {
        std::string move_str = move_to_string(piece_list_moves.moves[i]);
        piece_list_set.insert(move_str);
        std::cout << std::setw(2) << (i+1) << ". " << move_str << std::endl;
    }
    
    std::cout << std::endl << "=== Bitboard Implementation Moves ===" << std::endl;
    for (int i = 0; i < bitboard_moves.count; i++) {
        std::string move_str = move_to_string(bitboard_moves.moves[i]);
        bitboard_set.insert(move_str);
        std::cout << std::setw(2) << (i+1) << ". " << move_str << std::endl;
    }
    
    // Find differences
    std::set<std::string> only_in_piece_list;
    std::set<std::string> only_in_bitboard;
    
    std::set_difference(piece_list_set.begin(), piece_list_set.end(),
                       bitboard_set.begin(), bitboard_set.end(),
                       std::inserter(only_in_piece_list, only_in_piece_list.begin()));
                       
    std::set_difference(bitboard_set.begin(), bitboard_set.end(),
                       piece_list_set.begin(), piece_list_set.end(),
                       std::inserter(only_in_bitboard, only_in_bitboard.begin()));
    
    std::cout << std::endl << "=== DIFFERENCES ===" << std::endl;
    
    if (only_in_piece_list.empty() && only_in_bitboard.empty()) {
        std::cout << "✓ Both implementations generate identical moves!" << std::endl;
    } else {
        if (!only_in_piece_list.empty()) {
            std::cout << "Moves ONLY in piece list implementation (" << only_in_piece_list.size() << "):" << std::endl;
            for (const auto& move : only_in_piece_list) {
                std::cout << "  + " << move << std::endl;
            }
        }
        
        if (!only_in_bitboard.empty()) {
            std::cout << "Moves ONLY in bitboard implementation (" << only_in_bitboard.size() << "):" << std::endl;
            for (const auto& move : only_in_bitboard) {
                std::cout << "  + " << move << std::endl;
            }
        }
    }
    
    std::cout << std::endl << "=== SUMMARY ===" << std::endl;
    std::cout << "Traditional piece list moves: " << piece_list_moves.count << std::endl;
    std::cout << "Bitboard implementation moves: " << bitboard_moves.count << std::endl;
    std::cout << "Difference: " << (int)piece_list_moves.count - (int)bitboard_moves.count << std::endl;
    
    return 0;
}