#include "src/bitboard_position.hpp"
#include "src/bitboard_movegen_pure.hpp"
#include <iostream>
#include <iomanip>
#include <vector>
#include <set>
#include <algorithm>

using namespace BitboardMoveGen;

// Convert function
SimpleBitboardMove convert_move(const BitboardMoveList::BitboardMove& move) {
    SimpleBitboardMove simple_move;
    simple_move.from_64 = move.from_64;
    simple_move.to_64 = move.to_64;
    simple_move.is_capture = move.is_capture;
    simple_move.is_ep_capture = move.is_ep_capture;
    simple_move.is_castling = move.is_castling;
    simple_move.is_promotion = move.is_promotion;
    simple_move.promotion_type = move.promotion_type;
    return simple_move;
}

std::string move_to_string(const SimpleBitboardMove& move) {
    char from_file = 'a' + (move.from_64 % 8);
    char from_rank = '1' + (move.from_64 / 8);
    char to_file = 'a' + (move.to_64 % 8);
    char to_rank = '1' + (move.to_64 / 8);

    std::string result;
    result += from_file;
    result += from_rank;
    result += to_file;
    result += to_rank;

    if (move.is_promotion) {
        switch (move.promotion_type) {
            case PieceType::Queen: result += "q"; break;
            case PieceType::Rook: result += "r"; break;
            case PieceType::Bishop: result += "b"; break;
            case PieceType::Knight: result += "n"; break;
            default: break;
        }
    }

    return result;
}

int main() {
    std::cout << "=== Finding Missing Moves in Kiwipete Position ===\n\n";

    // Kiwipete position FEN
    std::string fen = "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1";
    std::cout << "Position: " << fen << "\n\n";

    // Expected legal moves from known reference (all 48 expected moves)
    std::set<std::string> expected_moves = {
        "a1b1", "a1c1", "a1d1", "a2a3", "a2a4", "b2b3", "c3a4", "c3b1", "c3b5", "c3d1",
        "d2c1", "d2e3", "d2f4", "d2g5", "d2h6", "d5d6", "d5e6", "e1c1", "e1d1", "e1f1",
        "e1g1", "e2a6", "e2b5", "e2c4", "e2d1", "e2d3", "e2f1", "e5c4", "e5c6", "e5d3",
        "e5d7", "e5f7", "e5g4", "e5g6", "f3d3", "f3e3", "f3f4", "f3f5", "f3f6", "f3g3",
        "f3g4", "f3h3", "f3h5", "g2g3", "g2g4", "g2h3", "h1f1", "h1g1"
    };

    BitboardPosition pos;
    if (!pos.set_from_fen(fen)) {
        std::cout << "ERROR: Failed to parse FEN!\n";
        return 1;
    }

    // Generate moves using our function
    BitboardMoveList moves;
    generate_legal_moves(pos, moves);

    std::set<std::string> actual_moves;
    std::vector<std::string> actual_move_list;

    std::cout << "=== MOVES GENERATED BY OUR ENGINE ===\n";
    for (const auto& move : moves.moves) {
        SimpleBitboardMove simple_move = convert_move(move);
        std::string move_str = move_to_string(simple_move);
        actual_moves.insert(move_str);
        actual_move_list.push_back(move_str);
        std::cout << move_str << " ";
    }
    std::cout << "\n\nTotal generated: " << actual_moves.size() << "\n";
    std::cout << "Expected total: " << expected_moves.size() << "\n\n";

    // Find missing moves (in expected but not in actual)
    std::cout << "=== MISSING MOVES (Expected but not generated) ===\n";
    std::vector<std::string> missing_moves;
    for (const auto& move : expected_moves) {
        if (actual_moves.find(move) == actual_moves.end()) {
            missing_moves.push_back(move);
            std::cout << move << " ";
        }
    }
    if (missing_moves.empty()) {
        std::cout << "(none)";
    }
    std::cout << "\nMissing count: " << missing_moves.size() << "\n\n";

    // Find extra moves (in actual but not in expected)
    std::cout << "=== EXTRA MOVES (Generated but not expected) ===\n";
    std::vector<std::string> extra_moves;
    for (const auto& move : actual_moves) {
        if (expected_moves.find(move) == expected_moves.end()) {
            extra_moves.push_back(move);
            std::cout << move << " ";
        }
    }
    if (extra_moves.empty()) {
        std::cout << "(none)";
    }
    std::cout << "\nExtra count: " << extra_moves.size() << "\n\n";

    // Analyze missing moves by piece type
    if (!missing_moves.empty()) {
        std::cout << "=== ANALYSIS OF MISSING MOVES ===\n";

        std::vector<std::string> king_moves, queen_moves, rook_moves, bishop_moves, knight_moves, pawn_moves;

        for (const auto& move : missing_moves) {
            char from_file = move[0];
            char from_rank = move[1];

            // Analyze by starting square to determine piece type
            if ((from_rank == '1' && (from_file == 'e')) || (from_rank == '1' && (from_file == 'e'))) {
                king_moves.push_back(move);
            } else if (from_file == 'f' && from_rank == '3') {
                queen_moves.push_back(move);
            } else if ((from_file == 'a' || from_file == 'h') && from_rank == '1') {
                rook_moves.push_back(move);
            } else if ((from_file == 'd' || from_file == 'e') && from_rank == '2') {
                bishop_moves.push_back(move);
            } else if ((from_file == 'c' || from_file == 'e') && (from_rank == '3' || from_rank == '5')) {
                knight_moves.push_back(move);
            } else if (from_rank == '2' || from_rank == '7') {
                pawn_moves.push_back(move);
            }
        }

        if (!king_moves.empty()) {
            std::cout << "King moves missing: ";
            for (const auto& move : king_moves) std::cout << move << " ";
            std::cout << "\n";
        }
        if (!queen_moves.empty()) {
            std::cout << "Queen moves missing: ";
            for (const auto& move : queen_moves) std::cout << move << " ";
            std::cout << "\n";
        }
        if (!rook_moves.empty()) {
            std::cout << "Rook moves missing: ";
            for (const auto& move : rook_moves) std::cout << move << " ";
            std::cout << "\n";
        }
        if (!bishop_moves.empty()) {
            std::cout << "Bishop moves missing: ";
            for (const auto& move : bishop_moves) std::cout << move << " ";
            std::cout << "\n";
        }
        if (!knight_moves.empty()) {
            std::cout << "Knight moves missing: ";
            for (const auto& move : knight_moves) std::cout << move << " ";
            std::cout << "\n";
        }
        if (!pawn_moves.empty()) {
            std::cout << "Pawn moves missing: ";
            for (const auto& move : pawn_moves) std::cout << move << " ";
            std::cout << "\n";
        }
    }

    std::cout << "\n=== SUMMARY ===\n";
    if (missing_moves.empty() && extra_moves.empty()) {
        std::cout << "✅ Perfect match! All moves are correct.\n";
    } else {
        std::cout << "❌ Discrepancy found:\n";
        std::cout << "  Missing: " << missing_moves.size() << " moves\n";
        std::cout << "  Extra: " << extra_moves.size() << " moves\n";
        std::cout << "  Net difference: " << (int)actual_moves.size() - (int)expected_moves.size() << "\n";
    }

    return 0;
}